import {
	PRIVATE_GOOGLE_API_AUTH_PROVIDER_X509_CERT_URL,
	PRIVATE_GOOGLE_API_AUTH_URI,
	PRIVATE_GOOGLE_API_CLIENT_EMAIL,
	PRIVATE_GOOGLE_API_CLIENT_ID,
	PRIVATE_GOOGLE_API_CLIENT_X509_CERT_URL,
	PRIVATE_GOOGLE_API_PRIVATE_KEY,
	PRIVATE_GOOGLE_API_PRIVATE_KEY_ID,
	PRIVATE_GOOGLE_API_PROJECT_ID,
	PRIVATE_GOOGLE_API_TOKEN_URI,
	PRIVATE_GOOGLE_API_TYPE,
	PRIVATE_GOOGLE_API_UNIVERSE_DOMAIN
} from '$env/static/private';

const credentials = {
	type: PRIVATE_GOOGLE_API_TYPE,
	project_id: PRIVATE_GOOGLE_API_PROJECT_ID,
	private_key_id: PRIVATE_GOOGLE_API_PRIVATE_KEY_ID,
	private_key: PRIVATE_GOOGLE_API_PRIVATE_KEY,
	client_email: PRIVATE_GOOGLE_API_CLIENT_EMAIL,
	client_id: PRIVATE_GOOGLE_API_CLIENT_ID,
	auth_uri: PRIVATE_GOOGLE_API_AUTH_URI,
	token_uri: PRIVATE_GOOGLE_API_TOKEN_URI,
	auth_provider_x509_cert_url: PRIVATE_GOOGLE_API_AUTH_PROVIDER_X509_CERT_URL,
	client_x509_cert_url: PRIVATE_GOOGLE_API_CLIENT_X509_CERT_URL,
	universe_domain: PRIVATE_GOOGLE_API_UNIVERSE_DOMAIN
};

export default credentials;
